### ISSUE TITLE
discussion

### ISSUE THREAD

**Issue by jhonalino** [soramitsu/fearless-utils#17]
just opening this for discussion for now. 
I just pulled some metadata on polkadot js app source code

https://github.com/polkadot-js/apps/blob/master/packages/apps-config/src/endpoints/productionRelayKusama.ts//https://github.com/polkadot-js/apps/tree/master/packages/apps-config/src/ui/logos/chains

**Comment by jhonalino** [comment]
but yeah this repo if we can pool data here would be really nice. 
I'm thinking data such as token, twitter and social medias. but I wonder how that would work? we probably have to work with parachains devs. or some way for them to easily add their metadata.

**Comment by valentunn** [comment]
Hi, we mostly keep state up-to-date by ourselves, but some teams (i.e. Karura) have already been contributed to this repo (see merged PRs)
A agree that it would be great if other teams will also collaborate with us and contribute here 
About social media links - this repo was created as a helper tool for Fearless Wallet, where we do not display social links for now. 
But I think such fields can be added easily since it produces no harm for our App

@antonkhvorov what do you think?

**Comment by antonkhvorov** [comment]
@valentunn I agree with you

@jhonalino feel free to suggest any improvement to the data format. 
Take into the account that sometimes its hard to get info from the teams, even about the rewards - as an example take a look for SubGame and Mars (Ares Protocol) projects - there are no public information about their crowdloans
